### ISSUE TITLE
file

### ISSUE THREAD

**Issue by SHAOTAO1998** [HindA12/YieldPrediction#1]
Can you share the files used in the code?Enter whether it is an image or a numeric value.

**Comment by HindA12** [comment]
Unfortunately, the data utilized in this code is confidential and cannot be disclosed. I'm referring not to the images themselves, but rather to the yield of each plot of land as depicted by the images.

**Comment by SHAOTAO1998** [comment]
I understand not sharing yield data. Is it the image you entered for training?

**Comment by SHAOTAO1998** [comment]
Can you share the image and paper?&nbsp;


------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "HindA12/YieldPrediction"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2023年8月25日(星期五) 晚上8:06
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [HindA12/YieldPrediction] file (Issue #1)





 
Unfortunately, the data utilized in this code is confidential and cannot be disclosed. I'm referring not to the images themselves, but rather to the yield of each plot of land as depicted by the images.
